version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: portfolio_wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: portfolio_db
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./data/wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - portfolio_network

  db:
    image: mysql:8.0
    container_name: portfolio_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - portfolio_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: portfolio_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress_password
    depends_on:
      - db
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge

volumes:
  mysql_data:
  wordpress_data:
